### ISSUE TITLE
Are notifications supported without Nest Aware?

### ISSUE THREAD

**Issue by fjs21** [Brandawg93/homebridge-nest-cam#160]
I get Nest App notifications on my iPhone but nothing via the Home app. I've checked and notifications are set to on for the Nest Cam. Other notifications work, e.g. Ring based notifications in Home. Nest cam works fine otherwise can view snap shots and live cam just fine on iPhone and watch. I do not have an active subscription to Nest Aware and was wondering if this was the issue. Thanks.

**Comment by Brandawg93** [comment]
Actually, I'm not sure. I have the Nest aware subscription and didn't want to cancel it to test the feature. In theory, it should work. You should see a single motion sensor in the camera's accessories. Do you see that?

**Comment by Brandawg93** [comment]
What iOS version are you running?

**Comment by fjs21** [comment]
I do see the motion sensor but it never "triggers" even if I get an alert from the Nest app.

**Comment by fjs21** [comment]
I'm running 13.5.1 (17F80)

**Comment by Brandawg93** [comment]
If you run homebridge in debug mode, do you see a line that says `Setting camera Motion to true`? I'm just curious if you are having the same issues as others.

**Comment by fjs21** [comment]
Will give that a go and report back

**Comment by Brandawg93** [comment]
I was able to create a test to confirm this is working. Do you have only one sensor for motion or three sensors for motion, person, and sound? I may not correctly be capturing that you don't have a Nest aware subscription.

**Comment by fjs21** [comment]
I see all three sensors.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Brandawg93** [comment]
That's definitely the issue then. Nest doesn't send notifications for person or sound without the Nest Aware subscription. Let me see if I can find a way to know whether a camera has Nest Aware or not.

**Comment by Brandawg93** [comment]
Ok. I've published a test that should only show one motion sensor and should hopefully trigger it with motion. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`. I'd appreciate it if you could try it out and let me know if it works for you.

**Comment by Brandawg93** [comment]
Whoops...Fixed a small bug. Should be good now. It will be `4.1.1-test.1`.

**Comment by fjs21** [comment]
I tried it. Still getting three sensors and no notifications.

**Comment by Brandawg93** [comment]
Ok. It's difficult for me to determine when a camera has the Nest Aware subscription since I cannot see what one looks like without the subscription. If you're up for it, I could use your help with this.

- Go to https://home.nest.com/ in chrome
- Click the three dots in the top right > More Tools > Developer Tools
- Click the `Network` tab
- Refresh the page
- Search for `cameras.get_owned_and_member_of_with_properties`
- Click it and click `Response`
- Copy and paste that here

With that, I can see what your cameras' settings look like without the Nest Aware subscription vs my cameras with the subscription.

**Comment by fjs21** [comment]
I’ll give it a try but will likely be a few days before I get to it due to other commitments.

**Comment by Brandawg93** [comment]
I went ahead and created test `4.1.1-test.2` which will show all three motion sensors, but only the 'Motion' sensor will work. Let me know if it triggers for you.

**Comment by fjs21** [comment]
I captured the Response as you indicated. Is there a way I can directly message you the Response (more securely)? It seems that it might contain a fair bit of info that might not be ideal on a public board.

**Comment by Brandawg93** [comment]
Sure. Feel free to message me on the discord server. The link is in the README.

**Comment by Brandawg93** [comment]
This may be fixed in v4.3.0.

**Comment by Brandawg93** [comment]
This should be fixed now. If not, feel free to reopen this issue.
