### ISSUE TITLE
Structure name feature does not work

### ISSUE THREAD

**Issue by axelbrunger** [Brandawg93/homebridge-nest-cam#191]
I have two Nest homes with different Structure IDs.  However, when I specify the Structure name in the Advanced Settings, it does not seem to have any effect. I tried either using the Structure ID or the name of the home.  In other words, the cameras in both homes are always added to the Homebridge regardless what I specify in the Structure Name field. 

I'm running a Homebridge server on a Mac Mini with the latest Mac OS.

Here is the relevant entry in the config:

...
 "ffmpegCodec": "libx264",
            "options": {
                "streamQuality": 3,
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "importantOnly": true,
                "motionDetection": true,
                "streamingSwitch": true,
                "chimeSwitch": true,
                "doorbellAlerts": true,
                "doorbellSwitch": true,
                "audioSwitch": true,
                "structures": [
                    "<my structure id>"
                ]
            },
            "platform": "Nest-cam"
...
Best regards,
Axel

**Comment by Brandawg93** [comment]
I've actually been working on this today. I've published a new test copy of the plugin that should fix this issue. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`. It will generate your Nest structures automatically in config-ui. Let me know if this fixes your issue!

**Comment by axelbrunger** [comment]
Thank you so much. The new test copy fixes my issue! Let me know when it’s available in the main version



On Aug 18, 2020, at 8:56 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



I've actually been working on this today. I've published a new test copy of the plugin that should fix this issue. You can install it via npm -g i homebridge-nest-cam@test --unsafe-perm. It will generate your Nest structures automatically in config-ui. Let me know if this fixes your issue!

**Comment by axelbrunger** [comment]
I just tried the test version in the other home but the Settings in the GUI does not work anymore.

On Aug 18, 2020, at 9:40 PM, Axel T Brunger <brunger@stanford.edu<mailto:brunger@stanford.edu>> wrote:

Thank you so much. The new test copy fixes my issue! Let me know when it’s available in the main version



On Aug 18, 2020, at 8:56 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



I've actually been working on this today. I've published a new test copy of the plugin that should fix this issue. You can install it via npm -g i homebridge-nest-cam@test --unsafe-perm. It will generate your Nest structures automatically in config-ui. Let me know if this fixes your issue!

**Comment by Brandawg93** [comment]
What do you mean "in the other home"?

**Comment by axelbrunger** [comment]
On the other computer in the other home

Sent from my iPhone

On Aug 18, 2020, at 9:46 PM, Brandon McFarlin <notifications@github.com> wrote:

﻿

What do you mean "in the other home"?

**Comment by Brandawg93** [comment]
Are you running two instances of homebridge? Or are you running just one instance with multiple structures selected?

**Comment by Brandawg93** [comment]
Also, could you elaborate on the settings being broken? Do they not show up at all? Or can you select structures, but they don't filter the cameras properly?

**Comment by axelbrunger** [comment]
Two entirely separate instances of Homebridge, one in each home.  See the attached screenshot that illustrates the problem. The settings menu works fine with the released version of nest-cam.

[cid:58889A20-7EAB-4A4E-864E-B9F2478D0FB2-L0-001]


Sent from my iPad

On Aug 18, 2020, at 9:59 PM, Brandon McFarlin <notifications@github.com> wrote:

﻿

Also, could you elaborate on the settings being broken? Do they not show up at all? Or can you select structures, but they don't filter the cameras properly?

**Comment by Brandawg93** [comment]
Github doesn't do screenshots well. You could either upload it to imgur and post the link or you could post it on the official discord server under my channel.

**Comment by axelbrunger** [comment]
Here is a link to the screenshot: 

https://share.icloud.com/photos/06ufCy-YPgocCfDxpT_7BIQwg

**Comment by Brandawg93** [comment]
I see the issue. I'll take a look at it tomorrow and let you know when I publish a new test.

**Comment by Brandawg93** [comment]
It was actually a simple fix. I published a new test that should fix the issue. You can install it with the previous command.

**Comment by axelbrunger** [comment]
Just tried. Same issue.



On Aug 18, 2020, at 10:35 PM, Brandon McFarlin <notifications@github.com> wrote:

﻿

It was actually a simple fix. I published a new test that should fix the issue. You can install it with the previous command.

**Comment by Brandawg93** [comment]
If you wouldn't mind helping me with this, I would appreciate it. There is a file locatated in the same directory as your `config.json` file. Its named `.homebridge-nest-cam-v1.schema.json`. You should see it being used in your logs when you try to look at your settings. Could you copy the contents of that file here? It may be hidden in that directory so you may need to use `ls -all` to see it.

**Comment by Brandawg93** [comment]
Ok, I think I fixed it this time. Let me know if the latest test works for you.

**Comment by axelbrunger** [comment]
Still doesn’t work. 

First, I deleted the offending file .homebridge-nest-cam-v1.schema.json
Here is the one that didn’t work:


{"pluginAlias":"Nest-cam","pluginType":"platform","dynamicSchemaVersion":1,"singular":true,"headerDisplay":"Instructions for setting up the config can be found on the [Github](https://github.com/Brandawg93/homebridge-nest-cam#setting-up-the-configjson).","schema":{"googleAuth":{"title":"Google Authentication","type":"object","properties":{"issueToken":{"title":"Issue Token","type":"string","default":"","required":true},"cookies":{"title":"Cookies","type":"string","default":"","required":true},"apiKey":{"title":"API Key","type":"string","default":"","required":true}}},"ffmpegCodec":{"title":"ffmpeg Codec","type":"string","default":"libx264","required":true,"description":"For best results use \"libx264\". The \"copy\" codec is not recommended but may work for less powerful devices."},"options":{"title":"Advanced Settings","expandable":true,"type":"object","properties":{"streamQuality":{"title":"Stream Quality","description":"The quality of the stream from LOW to HIGH. (Higher quality means better picture but slower stream)","type":"integer","default":3,"minimum":1,"maximum":3},"alertCheckRate":{"title":"Alert Check Rate","description":"How often to check for alerts? (seconds)","type":"integer","default":10,"minimum":2,"maximum":60},"alertCooldownRate":{"title":"Alert Cooldown Rate","description":"How long between consecutive alert notifications? (seconds)","type":"integer","default":180,"minimum":60,"maximum":300},"alertTypes":{"title":"Alert Types","description":"What type of alerts to receive","type":"array","items":{"title":"Alert Type","type":"string","oneOf":[{"title":"Motion","enum":["Motion"]},{"title":"Sound","enum":["Sound"]},{"title":"Person","enum":["Person"]},{"title":"Package Retrieved","enum":["Package Retrieved"]},{"title":"Package Delivered","enum":["Package Delivered"]},{"title":"Face","enum":["Face"]},{"title":"Zone","enum":["Zone"]}]}},"importantOnly":{"title":"Important Events Only","description":"Only send notifications on events considered important?","type":"boolean","default":true},"motionDetection":{"title":"Motion Detection","type":"boolean","default":true},"streamingSwitch":{"title":"Streaming Switch","type":"boolean","default":true},"chimeSwitch":{"title":"Indoor Chime Switch","type":"boolean","default":true},"doorbellAlerts":{"title":"Doorbell Alerts","type":"boolean","default":true},"doorbellSwitch":{"title":"Doorbell Switch","type":"boolean","default":true},"audioSwitch":{"title":"Audio Switch","type":"boolean","default":true},"pathToFfmpeg":{"title":"Path to FFMPEG","description":"In order to use a custom FFMPEG build, add the path to the FFMPEG binary here. Otherwise, leave blank.","type":"string","placeholder":"/path/to/ffmpeg","default":""},"structures":{"title":"Structures","description":"Restart homebridge after logging in to see available structures.","type":"array","items":{"title":"Structure Name","type":"string","oneOf":[]}}}}}}



Then uninstalled the plugin and reinstalled the plugin.

This time, I’m able to enter the fields in the Settings menu.

However, the plugin does not recognize any cameras anymore. Here is the current

.homebridge-nest-cam-v1.schema.json:

{"pluginAlias":"Nest-cam","pluginType":"platform","dynamicSchemaVersion":1,"singular":true,"headerDisplay":"Instructions for setting up the config can be found on the [Github](https://github.com/Brandawg93/homebridge-nest-cam#setting-up-the-configjson).","schema":{"googleAuth":{"title":"Google Authentication","type":"object","properties":{"issueToken":{"title":"Issue Token","type":"string","default":"","required":true},"cookies":{"title":"Cookies","type":"string","default":"","required":true},"apiKey":{"title":"API Key","type":"string","default":"","required":true}}},"ffmpegCodec":{"title":"ffmpeg Codec","type":"string","default":"libx264","required":true,"description":"For best results use \"libx264\". The \"copy\" codec is not recommended but may work for less powerful devices."},"options":{"title":"Advanced Settings","expandable":true,"type":"object","properties":{"streamQuality":{"title":"Stream Quality","description":"The quality of the stream from LOW to HIGH. (Higher quality means better picture but slower stream)","type":"integer","default":3,"minimum":1,"maximum":3},"alertCheckRate":{"title":"Alert Check Rate","description":"How often to check for alerts? (seconds)","type":"integer","default":10,"minimum":2,"maximum":60},"alertCooldownRate":{"title":"Alert Cooldown Rate","description":"How long between consecutive alert notifications? (seconds)","type":"integer","default":180,"minimum":60,"maximum":300},"alertTypes":{"title":"Alert Types","description":"What type of alerts to receive","type":"array","items":{"title":"Alert Type","type":"string","oneOf":[{"title":"Motion","enum":["Motion"]},{"title":"Sound","enum":["Sound"]},{"title":"Person","enum":["Person"]},{"title":"Package Retrieved","enum":["Package Retrieved"]},{"title":"Package Delivered","enum":["Package Delivered"]},{"title":"Face","enum":["Face"]},{"title":"Zone","enum":["Zone"]}]}},"importantOnly":{"title":"Important Events Only","description":"Only send notifications on events considered important?","type":"boolean","default":true},"motionDetection":{"title":"Motion Detection","type":"boolean","default":true},"streamingSwitch":{"title":"Streaming Switch","type":"boolean","default":true},"chimeSwitch":{"title":"Indoor Chime Switch","type":"boolean","default":true},"doorbellAlerts":{"title":"Doorbell Alerts","type":"boolean","default":true},"doorbellSwitch":{"title":"Doorbell Switch","type":"boolean","default":true},"audioSwitch":{"title":"Audio Switch","type":"boolean","default":true},"pathToFfmpeg":{"title":"Path to FFMPEG","description":"In order to use a custom FFMPEG build, add the path to the FFMPEG binary here. Otherwise, leave blank.","type":"string","placeholder":"/path/to/ffmpeg","default":""},"structures":{"title":"Structures","description":"Restart homebridge after logging in to see available structures.","type":"array","items":{"title":"Structure Name","type":"string"}}}}}}



and the log:


[8/19/2020, 6:16:17 AM] Homebridge is running on port 51826.
[8/19/2020, 6:17:14 AM] [Config] [homebridge-nest-cam] dynamic schema path: /Users/admin/.homebridge/.homebridge-nest-cam-v1.schema.json
[8/19/2020, 6:17:14 AM] [Config] [homebridge-nest-cam] dynamic schema loaded from: /Users/admin/.homebridge/.homebridge-nest-cam-v1.schema.json
[8/19/2020, 6:20:14 AM] [Config] [homebridge-nest-cam] dynamic schema path: /Users/admin/.homebridge/.homebridge-nest-cam-v1.schema.json
[8/19/2020, 6:20:14 AM] [Config] [homebridge-nest-cam] dynamic schema loaded from: /Users/admin/.homebridge/.homebridge-nest-cam-v1.schema.json
[8/19/2020, 6:20:58 AM] [Config] [homebridge-nest-cam] dynamic schema path: /Users/admin/.homebridge/.homebridge-nest-cam-v1.schema.json
[8/19/2020, 6:20:58 AM] [Config] [homebridge-nest-cam] dynamic schema loaded from: /Users/admin/.homebridge/.homebridge-nest-cam-v1.schema.json
[8/19/2020, 6:21:11 AM] [Config] Changes to config.json saved.
[8/19/2020, 6:21:13 AM] [Config] Homebridge restart request received
[8/19/2020, 6:21:14 AM] [Config] No restart command defined, killing process...
[8/19/2020, 6:21:14 AM] Got SIGTERM, shutting down Homebridge...
[8/19/2020, 6:21:19 AM] Loaded config.json with 0 accessories and 5 platforms.
[8/19/2020, 6:21:19 AM] ---
[8/19/2020, 6:21:19 AM] Loaded plugin: homebridge-camera-ffmpeg@2.4.7
[8/19/2020, 6:21:19 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[8/19/2020, 6:21:19 AM] ---
[8/19/2020, 6:21:19 AM] Loaded plugin: homebridge-config-ui-x@4.26.0
[8/19/2020, 6:21:19 AM] Registering platform 'homebridge-config-ui-x.config'
[8/19/2020, 6:21:19 AM] ---
[8/19/2020, 6:21:19 AM] Loaded plugin: homebridge-doorbird@1.0.0
[8/19/2020, 6:21:19 AM] Registering platform 'homebridge-doorbird.Doorbird'
[8/19/2020, 6:21:19 AM] ---
[8/19/2020, 6:21:19 AM] Loaded plugin: homebridge-dummy@0.4.1
[8/19/2020, 6:21:19 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[8/19/2020, 6:21:19 AM] ---
[8/19/2020, 6:21:19 AM] Loaded plugin: homebridge-envisalink@0.2.12
[8/19/2020, 6:21:19 AM] Registering platform 'homebridge-envisalink.Envisalink'
[8/19/2020, 6:21:19 AM] ---
[8/19/2020, 6:21:20 AM] Loaded plugin: homebridge-nest@4.4.6
[8/19/2020, 6:21:20 AM] Registering platform 'homebridge-nest.Nest'
[8/19/2020, 6:21:20 AM] ---
[8/19/2020, 6:21:20 AM] Loaded plugin: homebridge-nest-cam@4.6.2-test.2
[8/19/2020, 6:21:20 AM] Registering platform 'homebridge-nest-cam.Nest-cam'
[8/19/2020, 6:21:20 AM] ---
[8/19/2020, 6:21:20 AM] Loading 5 platforms...
[8/19/2020, 6:21:20 AM] [Config] Initializing config platform...
[8/19/2020, 6:21:20 AM] [Config] Spawning homebridge-config-ui-x with PID 74455
[8/19/2020, 6:21:20 AM] [Nest] Initializing Nest platform...
[8/19/2020, 6:21:20 AM] [Nest] Fetching Nest devices.
[8/19/2020, 6:21:20 AM] [Doorbird] Initializing Doorbird platform...
[8/19/2020, 6:21:20 AM] [Envisalink] Initializing Envisalink platform...
[8/19/2020, 6:21:20 AM] [Envisalink] Configuring Envisalink platform,  Host: 10.0.1.159, port: undefined, type: DSC
[8/19/2020, 6:21:20 AM] [Envisalink] Generated UUID 36f431e8-a869-4e88-b1aa-c18193e6f801 for accessory ID envisalink.1
[8/19/2020, 6:21:20 AM] [Envisalink] Generated UUID 769cc457-047f-4c76-ab44-8fcd67570fcf for accessory ID envisalink.1.1
[8/19/2020, 6:21:20 AM] [Envisalink] Starting node alarm proxy...
[8/19/2020, 6:21:20 AM] [Envisalink] Zone Config: 1
[8/19/2020, 6:21:20 AM] [Envisalink] User Program Config: null
[8/19/2020, 6:21:20 AM] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[8/19/2020, 6:21:20 AM] Initializing platform accessory '1'...
[8/19/2020, 6:21:20 AM] Initializing platform accessory 'Front door'...
[8/19/2020, 6:21:20 AM] [Nest-cam] Initializing Nest-cam platform...
server bound
actual connected
Login Request Response: 3 
login requested... sending response...
sendcommand 005user54
Command 005 Acknowledged
Login Request Response: 1 
successfully logged in!  getting current data...
sendcommand 00191
Command 001 Acknowledged
Zone 001 is restored
[8/19/2020, 6:21:20 AM] [Envisalink] System status changed to:  {
  zone: {
    '1': { send: 'restore', name: 'Zone Alarm Restore', code: '61000128' }
  },
  partition: {},
  user: {}
}
Zone 002 is restored
Zone 003 is restored
Zone 004 is restored
Zone 005 is restored
Zone 006 is restored
Zone 007 is restored
Zone 008 is restored
Zone 009 is restored
Zone 010 is restored
Zone 011 is restored
Zone 012 is restored
Zone 013 is restored
Zone 014 is restored
Zone 015 is restored
Zone 016 is restored
Zone 017 is restored
Zone 018 is restored
Zone 019 is restored
Zone 020 is restored
Zone 021 is restored
Zone 022 is restored
Zone 023 is restored
[8/19/2020, 6:21:20 AM] [Doorbird] Doorbird: Detected relay: 1 (primary).
[8/19/2020, 6:21:20 AM] [Doorbird] Doorbird: Connected to the Doorbird events API.
Zone 024 is restored
Zone 025 is restored
Zone 026 is restored
Zone 027 is restored
Zone 028 is restored
Zone 029 is restored
Zone 030 is restored
Zone 031 is restored
Zone 032 is restored
Zone 033 is restored
Zone 034 is restored
Zone 035 is restored
Zone 036 is restored
Zone 037 is restored
Zone 038 is restored
Zone 039 is restored
Zone 040 is restored
Zone 041 is restored
Zone 042 is restored
Zone 043 is restored
Zone 044 is restored
Zone 045 is restored
Zone 046 is restored
Zone 047 is restored
[8/19/2020, 6:21:21 AM] [Config] Homebridge Config UI X v4.26.0 is listening on :: port 8080
Zone 048 is restored
Zone 049 is restored
Zone 050 is restored
Zone 051 is restored
Zone 052 is restored
Zone 053 is restored
Zone 054 is restored
Zone 055 is restored
Zone 056 is restored
Zone 057 is restored
Zone 058 is restored
Zone 059 is restored
Zone 060 is restored
Zone 061 is restored
Zone 062 is restored
Zone 063 is restored
Zone 064 is restored
Partition 10 is Armed
[8/19/2020, 6:21:21 AM] [Envisalink] System status changed to:  {
  zone: {
    '1': { send: 'restore', name: 'Zone Alarm Restore', code: '61000128' }
  },
  partition: { '1': { send: 'armed', name: 'Partition Armed', code: '65210FE' } },
  user: {}
}
Set system status on accessory 1 to {"name":"Partition Armed","pre":"Partition","bytes":1,"post":"is Armed","send":"armed","action":"updatepartition","code":"652"}
Partition 2 is Busy
Partition 3 is Busy
Partition 4 is Busy
Partition 5 is Busy
Partition 6 is Busy
Partition 7 is Busy
Partition 8 is Busy
Trouble LED of Partition 1 is OFF
Trouble LED of Partition 2 is OFF
Trouble LED of Partition 3 is OFF
Trouble LED of Partition 4 is OFF
Trouble LED of Partition 5 is OFF
Trouble LED of Partition 6 is OFF
Trouble LED of Partition 7 is OFF
Trouble LED of Partition 8 is OFF
Keypad LED State: 82 
[8/19/2020, 6:21:27 AM] [Nest] Skipping device 09AA01AC10160J9X because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 6:21:27 AM] [Nest] Skipping device 09AA01AC09160542 because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 6:21:27 AM] [Nest] Skipping device 09AA01AC41150P1J because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 6:21:27 AM] [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01AC41150P60 structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 6:21:27 AM] [Nest] initing thermostat "Upstairs Hallway Thermostat": deviceId: 09AA01AC41150LM2 structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 6:21:27 AM] [Nest] Skipping device c9c66c70-ffa1-11e5-ac70-22000b5190f4 because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 6:21:27 AM] [Nest] initing home_away_sensor "Home Occupied - SF": deviceId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4 structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 6:21:27 AM] [Nest] Skipping device 00177A000003E9F0 because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 6:21:27 AM] [Nest] initing lock "Entryway Lock": deviceId: 00177A00000517FF structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 6:21:27 AM] Initializing platform accessory 'Living Room Thermostat'...
[8/19/2020, 6:21:27 AM] Initializing platform accessory 'Upstairs Hallway Thermostat'...
[8/19/2020, 6:21:27 AM] Initializing platform accessory 'Home Occupied - SF'...
[8/19/2020, 6:21:27 AM] Initializing platform accessory 'Entryway Lock'...
Setup Payload:
X-HM://002527W9KHEO5
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 962-20-440 │     
    └────────────┘     
                       
[8/19/2020, 6:21:27 AM] Homebridge is running on port 51826.




> On Aug 19, 2020, at 8:52 AM, Brandon McFarlin <notifications@github.com> wrote:
> 
> 
> Ok, I think I fixed it this time. Let me know if the latest test works for you.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

**Comment by Brandawg93** [comment]
It seems that your Nest-cam plugin didn't see any cameras connected to your account. That's why you were receiving the initial error, because it didn't see any structures. You saw them before because they remained cached in homebridge.

**Comment by axelbrunger** [comment]
My Nest account still has the cameras connected. So, I really don’t understand why the nest-cam plugin
does not recognize them anymore. I redid the authentication and also uninstalled the plugin and reinstalled it.

The authentication is correct since it works for the nest plugin.

Please advise.

On Aug 19, 2020, at 9:44 AM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



It seems that your Nest-cam plugin didn't see any cameras connected to your account. That's why you were receiving the initial error, because it didn't see any structures. You saw them before because they remained cached in homebridge.

**Comment by Brandawg93** [comment]
Are you running two homebridge instances on the same network?

**Comment by axelbrunger** [comment]
No. They are on entirely separate networks.

On Aug 19, 2020, at 12:50 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Are you running two homebridge instances on the same network?

**Comment by Brandawg93** [comment]
Ok. That's very odd. So when installing the latest version on one network, it works normally, but when installing the latest version on the second network, you see no cameras? Can you run homebridge in debug mode on the one that doesn't work and copy the output here?

**Comment by axelbrunger** [comment]
How do I turn on debug mode in homebridge?

On Aug 19, 2020, at 12:58 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Ok. That's very odd. So when installing the latest version on one network, it works normally, but when installing the latest version on the second network, you see no cameras? Can you run homebridge in debug mode on the one that doesn't work and copy the output here?

**Comment by Brandawg93** [comment]
Homebridge Settings => Homebridge Debug Mode

**Comment by axelbrunger** [comment]
I’m sorry, but there is no debug mode in Homebridge Settings. Just “Reset”, “Unpair Bridges”, “Reset Homebridge Accessory”.

On Aug 19, 2020, at 1:04 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Homebridge Settings => Homebridge Debug Mode

**Comment by Brandawg93** [comment]
When you start homebridge, start it with `homebridge -D`.

**Comment by axelbrunger** [comment]
Here is the result:

unifi:~ admin$ homebridge -D
[8/19/2020, 10:22:44 AM] Loaded config.json with 0 accessories and 4 platforms.
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loaded plugin: homebridge-camera-ffmpeg@2.4.7
[8/19/2020, 10:22:44 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loaded plugin: homebridge-config-ui-x@4.26.0
[8/19/2020, 10:22:44 AM] Registering platform 'homebridge-config-ui-x.config'
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loaded plugin: homebridge-doorbird@1.0.0
[8/19/2020, 10:22:44 AM] Registering platform 'homebridge-doorbird.Doorbird'
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loaded plugin: homebridge-dummy@0.4.1
[8/19/2020, 10:22:44 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loaded plugin: homebridge-nest@4.4.6
[8/19/2020, 10:22:44 AM] Registering platform 'homebridge-nest.Nest'
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loaded plugin: homebridge-nest-cam@4.6.1
[8/19/2020, 10:22:44 AM] Registering platform 'homebridge-nest-cam.Nest-cam'
[8/19/2020, 10:22:44 AM] ---
[8/19/2020, 10:22:44 AM] Loading 4 platforms...
[8/19/2020, 10:22:44 AM] [Config] Initializing config platform...
[8/19/2020, 10:22:44 AM] [Config] Spawning homebridge-config-ui-x with PID 2052
[8/19/2020, 10:22:44 AM] [Nest] Initializing Nest platform...
[8/19/2020, 10:22:44 AM] [Nest] Fetching Nest devices.
[8/19/2020, 10:22:44 AM] [Nest] Authenticating via Google.
[8/19/2020, 10:22:44 AM] [Doorbird] Initializing Doorbird platform...
[8/19/2020, 10:22:44 AM] [Nest-cam] Initializing Nest-cam platform...
[8/19/2020, 10:22:44 AM] [Nest-cam] Using motionDetection from config: true
[8/19/2020, 10:22:44 AM] [Nest-cam] Using doorbellAlerts from config: true
[8/19/2020, 10:22:44 AM] [Nest-cam] Using doorbellSwitch from config: true
[8/19/2020, 10:22:44 AM] [Nest-cam] Using streamingSwitch from config: true
[8/19/2020, 10:22:44 AM] [Nest-cam] Using chimeSwitch from config: true
[8/19/2020, 10:22:44 AM] [Nest-cam] Using audioSwitch from config: true
[8/19/2020, 10:22:44 AM] [Nest-cam] Defaulting structures to []
[8/19/2020, 10:22:44 AM] [Nest-cam] Setting Field Test to false
[8/19/2020, 10:22:44 AM] [Nest-cam] Authenticating via Google.
[8/19/2020, 10:22:44 AM] [Doorbird] Doorbird: Detected relay: 1 (primary).
[8/19/2020, 10:22:44 AM] [Doorbird] Doorbird: Connected to the Doorbird events API.
[8/19/2020, 10:22:46 AM] [Config] Homebridge Config UI X v4.26.0 is listening on :: port 8080
[8/19/2020, 10:22:46 AM] [Config] Error: listen EADDRINUSE: address already in use :::8080
[8/19/2020, 10:22:46 AM] [Config] Another process or service on this host is using port 8080.
[8/19/2020, 10:22:46 AM] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[8/19/2020, 10:22:46 AM] [Config] Ending process now.
[8/19/2020, 10:22:46 AM] Got SIGTERM, shutting down Homebridge...
[8/19/2020, 10:22:46 AM] [Nest] Authentication successful.
[8/19/2020, 10:22:51 AM] [Nest] Skipping device 09AA01AC10160J9X because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 10:22:51 AM] [Nest] Skipping device 09AA01AC09160542 because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 10:22:51 AM] [Nest] Skipping device 09AA01AC41150P1J because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 10:22:51 AM] [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01AC41150P60 structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 10:22:51 AM] [Nest] Temperature unit for Living Room Thermostat is: Fahrenheit
[8/19/2020, 10:22:51 AM] [Nest] Current temperature for Living Room Thermostat is: 27 °C / 80.5 °F
[8/19/2020, 10:22:51 AM] [Nest] Current humidity for Living Room Thermostat is: 50%
[8/19/2020, 10:22:51 AM] [Nest] Target temperature for Living Room Thermostat is: 19 °C / 66 °F
[8/19/2020, 10:22:51 AM] [Nest] Target heating/cooling state for Living Room Thermostat is: Heat
[8/19/2020, 10:22:51 AM] [Nest] Cooling threshold temperature for Living Room Thermostat is: 24.44444 °C / 76 °F
[8/19/2020, 10:22:51 AM] [Nest] Heating threshold temperature for Living Room Thermostat is: 19 °C / 66 °F
[8/19/2020, 10:22:51 AM] [Nest] Online status for Living Room Thermostat is: true
[8/19/2020, 10:22:51 AM] [Nest] Sunlight Correction Enabled for Living Room Thermostat is: true
[8/19/2020, 10:22:51 AM] [Nest] initing thermostat "Upstairs Hallway Thermostat": deviceId: 09AA01AC41150LM2 structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 10:22:51 AM] [Nest] Temperature unit for Upstairs Hallway Thermostat is: Fahrenheit
[8/19/2020, 10:22:51 AM] [Nest] Current temperature for Upstairs Hallway Thermostat is: 27.48999 °C / 81.5 °F
[8/19/2020, 10:22:51 AM] [Nest] Current humidity for Upstairs Hallway Thermostat is: 48%
[8/19/2020, 10:22:51 AM] [Nest] Target temperature for Upstairs Hallway Thermostat is: 19 °C / 66 °F
[8/19/2020, 10:22:51 AM] [Nest] Target heating/cooling state for Upstairs Hallway Thermostat is: Heat
[8/19/2020, 10:22:51 AM] [Nest] Cooling threshold temperature for Upstairs Hallway Thermostat is: 24.44444 °C / 76 °F
[8/19/2020, 10:22:51 AM] [Nest] Heating threshold temperature for Upstairs Hallway Thermostat is: 19 °C / 66 °F
[8/19/2020, 10:22:51 AM] [Nest] Online status for Upstairs Hallway Thermostat is: true
[8/19/2020, 10:22:51 AM] [Nest] Sunlight Correction Enabled for Upstairs Hallway Thermostat is: true
[8/19/2020, 10:22:51 AM] [Nest] Skipping device c9c66c70-ffa1-11e5-ac70-22000b5190f4 because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 10:22:51 AM] [Nest] initing home_away_sensor "Home Occupied - SF": deviceId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4 structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 10:22:51 AM] [Nest] Skipping device 00177A000003E9F0 because it is not in the required structure. Has c9c66c70-ffa1-11e5-ac70-22000b5190f4, looking for 39e9ecf0-ff95-11e5-ac70-22000b5190f4.
[8/19/2020, 10:22:51 AM] [Nest] initing lock "Entryway Lock": deviceId: 00177A00000517FF structureId: 39e9ecf0-ff95-11e5-ac70-22000b5190f4
[8/19/2020, 10:22:51 AM] [Nest] Locked (Current) for Entryway Lock is: 1
[8/19/2020, 10:22:51 AM] [Nest] Locked (Target) for Entryway Lock is: 1
[8/19/2020, 10:22:51 AM] Initializing platform accessory 'Living Room Thermostat'...
[8/19/2020, 10:22:51 AM] Initializing platform accessory 'Upstairs Hallway Thermostat'...
[8/19/2020, 10:22:51 AM] Initializing platform accessory 'Home Occupied - SF'...
[8/19/2020, 10:22:51 AM] Initializing platform accessory 'Entryway Lock'...
Setup Payload:
X-HM://002527W9KHEO5
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:



























Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 962-20-440 │
    └────────────┘

[8/19/2020, 10:22:51 AM] Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:85:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:236:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:974:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:192:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:164:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:163:5)
unifi:~ admin$



On Aug 19, 2020, at 1:11 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



When you start homebridge, start it with homebridge -D.

**Comment by Brandawg93** [comment]
Ok. It's able to connect to Nest properly, but it is not seeing any cameras in the account. It could be related to this:
> [8/19/2020, 10:22:51 AM] Error: listen EADDRINUSE: address already in use :::51826

That usually means you are running 2 homebridge instances on the same network.

**Comment by axelbrunger** [comment]
But there is only one instance running on that network!

On Aug 19, 2020, at 1:29 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Ok. It's able to connect to Nest properly, but it is not seeing any cameras in the account. It could be related to this:

[8/19/2020, 10:22:51 AM] Error: listen EADDRINUSE: address already in use :::51826

That usually means you are running 2 homebridge instances on the same network.

**Comment by Brandawg93** [comment]
It could be that there are two processes running homebridge on the same device at the same time.

**Comment by axelbrunger** [comment]
It doesn’t look like there are two instances running:

unifi:~ admin$ ps -A | grep home
  344 ??         0:04.43 /System/Library/PrivateFrameworks/HomeKitDaemon.framework/Support/homed
 1511 ??         0:02.57 homebridge
 1515 ??         0:03.52 homebridge-config-ui-x
 2485 ttys000    0:00.00 grep home

On Aug 19, 2020, at 1:32 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



It could be that there are two processes running homebridge on the same device at the same time.

**Comment by Brandawg93** [comment]
Does the latest version of homebridge-nest-cam still work? (4.6.1)

**Comment by axelbrunger** [comment]
No. The trouble started yesterday when I tried out your new test version.  It works in one home location, but not the other.

On Aug 19, 2020, at 1:37 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Does the latest version of homebridge-nest-cam still work? (4.6.1)

**Comment by Brandawg93** [comment]
Ok. I would try wiping that instance of homebridge and setting it up again. It may just be something weird in the homebridge cache. If you delete the `accessories` and `persist` folders, it will clear the cache.

**Comment by axelbrunger** [comment]
I just noticed that one of the cameras is offline as of last night. Could this be the problem? In the Nest app
all other cameras are showing properly, but this one does not connect and shows the spinning wheel. The
trouble is that I’m not in that location for quite some time to reset the camera.

Anyway, could this be the problem with the next-cam plugin - perhaps it is getting stuck since the one
camera is offline?

Please advise.



On Aug 19, 2020, at 1:43 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Ok. I would try wiping that instance of homebridge and setting it up again. It may just be something weird in the homebridge cache. If you delete the accessories and persist folders, it will clear the cache.

**Comment by Brandawg93** [comment]
That could definitely be the issue. The plugin is probably continually trying to get info on that camera before going to the next. Once that camera is fixed and they load again, they should get cached and it won't be a problem anymore.

**Comment by axelbrunger** [comment]
Thank you. Since I won’t be at that location for quite a while, I can’t test this right away.

A nice feature for your plugin would be to time out for a camera that is not connected for some reason,
but then connect the remaining cameras (as done by the Next App)?


On Aug 19, 2020, at 1:50 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



That could definitely be the issue. The plugin is probably continually trying to get info on that camera before going to the next. Once that camera is fixed and they load again, they should get cached and it won't be a problem anymore.

**Comment by Brandawg93** [comment]
Since the original issue is fixed, I'm going to close this. If you check your structure later on and are still having issues, let me know.

**Comment by axelbrunger** [comment]
I managed to delete the dead camera by going to my account on the Nest website. I then installed your latest version
of nest-cam at both home locations and was able to select the respective home name. It’s all working now. Thanks so much.

On Aug 19, 2020, at 3:08 PM, Brandon McFarlin <notifications@github.com<mailto:notifications@github.com>> wrote:



Since the original issue is fixed, I'm going to close this. If you check your structure later on and are still having issues, let me know.
