### ISSUE TITLE
npm update without of --unsafe-perm broke the ffmpeg plug-in

### ISSUE THREAD

**Issue by bogdanbun** [Brandawg93/homebridge-nest-cam#244]
**Describe the bug**
I don't think this is `homebridge-nest-cam` bug per say, but it would be nice to have some sort of "howto" to fix this problem.

After I upgraded all packages using the following command:

```
sudo npm -g update
```

I noticed a message which said that `ffmpeg` update failed. I realized that I was missing the `--unsafe-perm` parameter and updated the `ffmpeg` package explicitly (with that parameter). The `ffmpeg` got updated (to version 0.0.9), but ever since I'm getting this error when I'm trying to open the live stream:

```
[9/9/2020, 2:26:20 PM] [Nest-cam] FFMPEG is not installed. Please install it before using this plugin.
```

There are no extra messages even in debug mode.

I guess it is failing to locate the binary in the path, but I couldn't figure out why:

```
/usr/local/lib/node_modules/ffmpeg-for-homebridge/ffmpeg 
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

Perhaps there is some way to fix the path it is searching manually?

```
On what OS are you running homebridge: Debian 10
On what iOS version are you having issues: iOS 13.7
What camera types are having issues: Google Hello
Does this issue occur consistently or randomly: Consistently
If applicable, what was the last version that worked properly: 
```

**Comment by Brandawg93** [comment]
Can you use [homebridge-config-ui-x](https://www.npmjs.com/package/homebridge-config-ui-x)? It will update plugins properly. Otherwise, `npm install -g --unsafe-perm homebridge-nest-cam` will update the plugin as well.

**Comment by bogdanbun** [comment]
I didn't realize that `homebridge-config-ui-x` can be used to update plug-ins. I'll try that with the next update.

In the meantime, I tried updating the plug-in from command line, like you suggested, restarted the hombridge instance, but that did not resolve the problem. May I ask what is it actually looking for? I checked the code and it seems like it's checking the system path, but I'm not sure if I understand it correctly. Should I maybe add the `ffmpeg` path to the system defaults?

**Comment by Brandawg93** [comment]
> Should I maybe add the ffmpeg path to the system defaults?

Yes. The plugin will attempt to download a static ffmpeg binary, but you can change which one is used by pointing `"pathToFfmpeg"` to your system ffmpeg.

**Comment by bogdanbun** [comment]
Interesting... so I provided the full path to the `ffmpeg` binary in the `homebridge-nest-cam` config, and now I'm getting these messages, but still the live stream wouldn't start:

```
[9/9/2020, 3:33:03 PM] [Nest-cam] VIDEO command: ffmpeg -f,h264,-use_wallclock_as_timestamps,1,-r,30,-i,pipe:,-c:v,libx264,-preset,ultrafast,-tune,zerolatency,-pix_fmt,yuv420p,-payload_type,99,-ssrc,7417715,-f,rtp,-srtp_out_suite,AES_CM_128_HMAC_SHA1_80,-srtp_out_params,bADJasXUHC+QCB6GMpXezGV+0RFuRXg8Nxfhe/dA,srtp://X.X.X.X:62367?rtcpport=62367&localrtcpport=45701&pkt_size=1378
[9/9/2020, 3:33:03 PM] [Nest-cam] VIDEO: ffmpeg version 4.3.1
[9/9/2020, 3:33:03 PM] [Nest-cam] VIDEO:  Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[9/9/2020, 3:33:03 PM] [Nest-cam] AUDIO command: ffmpeg -c:a,libfdk_aac,-i,pipe:,-c:a,libfdk_aac,-profile:a,aac_eld,-ac,1,-ar,16k,-b:a,24k,-flags,+global_header,-payload_type,110,-ssrc,9720128,-f,rtp,-srtp_out_suite,AES_CM_128_HMAC_SHA1_80,-srtp_out_params,qozT2KTOv0TOYFMjQ1VL0jaEZ0vYkeFRcUw1ddzi,srtp://X.X.X.X:56071?rtcpport=56071&localrtcpport=41141&pkt_size=188
[9/9/2020, 3:33:03 PM] [Nest-cam] AUDIO: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[9/9/2020, 3:33:03 PM] [Nest-cam] RETURN AUDIO command: ffmpeg -hide_banner,-protocol_whitelist,pipe,udp,rtp,file,crypto,-f,sdp,-c:a,libfdk_aac,-i,pipe:0,-map,0:0,-c:a,libspeex,-frames_per_packet,4,-ac,1,-b:a,24k,-ar,16k,-f,data,pipe:1
[9/9/2020, 3:33:03 PM] [Nest-cam] waiting for socket to connect
[9/9/2020, 3:33:03 PM] [Nest-cam] Using HIGH quality stream.
[9/9/2020, 3:33:03 PM] [Nest-cam] waiting for socket to connect
[9/9/2020, 3:33:03 PM] [Nest-cam] [NexusStreamer] Connected
[9/9/2020, 3:33:04 PM] [Nest-cam] [NexusStreamer] OK
[9/9/2020, 3:33:04 PM] [Nest-cam] [NexusStreamer] Playback End
[9/9/2020, 3:33:04 PM] [Nest-cam] [NexusStreamer] Playback End
```

Is it possible that something else got broken, not only the actual path to the binary?

**Comment by Brandawg93** [comment]
Try clearing your cache (Homebridge Settings). It fixed the same issue in #236.

**Comment by Brandawg93** [comment]
This issue should be fixed in v5.2.2. If not, feel free to reopen this.

**Comment by bogdanbun** [comment]
It looks like my issue is still unresolved. The first time after updating to version 5.2.2 I got this message in the log when trying to start the stream:

```
[9/9/2020, 8:34:23 PM] Homebridge is running on port 51666.
[9/9/2020, 8:34:46 PM] [Nest-cam] [NexusStreamer] Connected
[9/9/2020, 8:34:56 PM] [Nest-cam] VIDEO:   libpostproc    55.  7.100 / 55.  7.100
[9/9/2020, 8:34:56 PM] [Nest-cam] [NexusStreamer] Disconnected
```

But then the `libpostproc` message went away and I get only the following lines now:

```
[9/9/2020, 8:38:09 PM] Homebridge is running on port 51666.
[9/9/2020, 8:38:26 PM] [Nest-cam] [NexusStreamer] Connected
[9/9/2020, 8:38:37 PM] [Nest-cam] [NexusStreamer] Disconnected
[9/9/2020, 8:38:50 PM] [Nest-cam] [NexusStreamer] Connected
[9/9/2020, 8:39:00 PM] [Nest-cam] [NexusStreamer] Disconnected
```

**Comment by Brandawg93** [comment]
Did you clear your cache?

**Comment by bogdanbun** [comment]
Do you mean the `Remove Single Cached Accessory` or `Remove All Cached Accessories` action?

**Comment by Brandawg93** [comment]
`Remove Single Cached Accessory` for each camera that is affected.

**Comment by bogdanbun** [comment]
Thank you for your help! That resolved the problem.
