### ISSUE TITLE
Talk audio is slow and distorted

### ISSUE THREAD

**Issue by cyberpower678** [Brandawg93/homebridge-nest-cam#248]
When trying to talk through an Outdoor IQ Cam, the user's audio comes out with at least 5 seconds delay and is stretched out.

**Comment by Brandawg93** [comment]
This is a known issue that I don't think can be resolved. Homekit sends back high-quality AAC audio for some reason which has to be converted to low-quality SPEEX for Nest to understand. This conversion process is very CPU intensive and distorts the audio. So far, I haven't found any way around this.

**Comment by Brandawg93** [comment]
I've published a new test that may actually make return audio much better. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`. Let me know if this makes a difference for you.

**Comment by Brandawg93** [comment]
This should be better in v5.2.3. If not, just let me know.

**Comment by cyberpower678** [comment]
It’s significantly better but still not perfect.  There are still some audio stutters and it still delays as much as 1 second, but it does not drag anymore.  It would be ideal if it can be improved some more.

**Comment by Brandawg93** [comment]
I'm not sure how much more I can improve, but I'll take one more stab at it.

**Comment by n0rt0nthec4t** [comment]
Issue I seem to get is "echo" when talking. Doesn't happen when using the nest app, so assuming some weird implementation  (or limitation) of the return audio coding. Been trying to look into it

**Comment by Brandawg93** [comment]
I get that too. Feel free to play around with the code. I'd be happy to answer any questions you have. I've tried a lot of different combinations of FFmpeg filters to mitigate the echo and distortion but haven't found the best combo yet.

**Comment by n0rt0nthec4t** [comment]
I think I might be in the rptsplitter code. I notice (atleast on my Nest Hello), that the payloadtype only appears to be 110 or 72. It looks like id 72 is a heart beat of some sort. The message length for 110 seems to sit on 31 until you talk back, than that increases.

**Comment by Brandawg93** [comment]
Correct. 72 is the RTCP for outgoing audio, whereas 110 is return audio RTP packets. The packet length 31 is a weird new feature of iOS 14. It is generated silence that they push back 24/7 as opposed to iOS 13 where nothing would come back until you started talking. I think the biggest issue is the conversion from AAC to SPEEX in FFmpeg. It is trying to take high-quality AAC and convert it to low-quality SPX which is causing the distortion.

**Comment by Brandawg93** [comment]
Return audio has been fixed in v5.4.0. For anyone interested, I was sending audio packets twice which caused it to be slow and distorted.
