### ISSUE TITLE
Linking Google account timeout

### ISSUE THREAD

**Issue by henryjrobertson** [Brandawg93/homebridge-nest-cam#250]
Hello, 
Trying to auth with the LINK ACCOUNT button ends up timing out and not generating tokens.

Looks like script runs, asks for user/pw, then logs “Finishing up...“ to Homebridge log but eventually times out. I can also see Chromium processes start, but couldn’t find any relevant logs/errors there. 

Side note: I’ve got 2FA on my Google account and it also doesn’t prompt for that so probably stuck somewhere before that? 

Happy to grab whatever logs you’d like.

Thanks!

**Comment by henryjrobertson** [comment]
Bah, looks like a duplicate of #223 . I’ll try that workaround.

**Comment by Brandawg93** [comment]
That fix is already implemented. Try using the process manually. In the root directory of the plugin, run `node dist/login.js -h` and try to login to your account.

**Comment by henryjrobertson** [comment]
Same results running manually.

**Comment by Brandawg93** [comment]
Ok. Are you using SMS based 2FA? Or Gmail app 2FA?

**Comment by henryjrobertson** [comment]
I’m using Gmail app 2FA - but I get the same results if I try to force an error by using a non-Gmail login credentials or real ones with the wrong password. I don’t think it’s getting that far...

**Comment by henryjrobertson** [comment]
So, I probably should have mentioned I’m running Homebridge on a Raspberry Pi? 

I think this could be caused by puppeteer and chromium being unhappy with each other. My box won’t launch with the -h flag passed in. Seems like a well documented issue trying to run headless Chromium on the PIs. I will probably just suck it up and pass in the tokens manually.

**Comment by Brandawg93** [comment]
I'm working on a fix. It's definitely a bug. I'll let you know when it's ready to test.

**Comment by Brandawg93** [comment]
Ok. I've created a new test that may fix your issue or at least get you a little further in the process. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`.

**Comment by henryjrobertson** [comment]
How should I test differently? Manually running script gives same Chromium
(probably RPi environment specific) errors.

**Comment by Brandawg93** [comment]
Try running without the `-h`.

**Comment by henryjrobertson** [comment]
Ack.

Same results without -h. Quickly gets to “finishing up” then sits for full
timeout.

**Comment by Brandawg93** [comment]
Did it notify you that you need to check the gmail app? I'm just curious if it got that far.

**Comment by henryjrobertson** [comment]
It did not. I can still give it gibberish logins and it doesn’t error, just
times out.

**Comment by Brandawg93** [comment]
It sounds like you may not have the latest test version. What version does the package.json file show you are using?

**Comment by henryjrobertson** [comment]
homebridge-nest-cam v5.2.4-test.0 from UI
Package.json: 5.2.4-test.0

**Comment by Brandawg93** [comment]
I've been doing a little more work on it. I've published a new test. 5.2.4-test.1. You should be able to use the same command as above but may need to use `npm -g i homebridge-nest-cam@5.2.4-test.1 --unsafe-perm`.

**Comment by Brandawg93** [comment]
If that doesn't work, you may want to try installing the plugin on a Mac or Windows and running it there with `-h`. The login process is independent of homebridge, so you can run it on any machine.

**Comment by henryjrobertson** [comment]
Still no luck on the RPi - but it does seem to have cleared up the
deprecation warnings for the await calls... so I am at least seeing that.
I’ll try it on a Mac this evening and report back.

**Comment by Brandawg93** [comment]
Great. Thanks for the help testing.

**Comment by henryjrobertson** [comment]
Worked first shot on the Mac. 2FA and all (gmail app).

**Comment by Brandawg93** [comment]
Interesting. So it must be an issue with the Raspberry pi and puppeteer. Did you try it again on the Pi recently? I found that my account got locked out for an hour because I was testing so much.

**Comment by Brandawg93** [comment]
I went ahead and published a new version (v5.2.4) with some of the fixes from your test copies and a few other things. Let me know if this helps the Pi version.

**Comment by henryjrobertson** [comment]
Sorry for delay in testing.

Using -h flag still fails, but if I ignore that I get to the creditials
part - which works! If I use a phony address or bad password it errors out
accordingly. Progress!

It does however, still time out after logging “Finishing up...”

I don’t receive and 2FA prompts like I do if I run it in Mac.

**Comment by Brandawg93** [comment]
Let me know if v5.2.5 fixes this issue.

**Comment by henryjrobertson** [comment]
No change: login.js errors on the -h flag, if I leave that out - it times
out on "finishing up".

I did some more poking around as well and I can get headless Chromium to
work with a manually installed version, but not the Puppeteer bundled one.
Besides passing a path -p /usr/bin/chromium-browser when I call your
install script is there anything else needed to bypass the Puppeteer
version?

**Comment by Brandawg93** [comment]
It shouldn't use the puppeteer version unless it absolutely has to. It attempts to install chromium manually first, then falls back to puppeteer.

**Comment by Brandawg93** [comment]
I've created a new test that should hopefully be more informative on timeouts. You can install via `npm -g i homebridge-nest-cam@5.2.6-test.2 --unsafe-perm`. Let me know what error is gives you in the console.

**Comment by Brandawg93** [comment]
That's very strange, but I'm happy it's working for you now! Thanks again for your help testing this. It really helps. These latest changes are now live in v5.2.6.
