### ISSUE TITLE
NEST plug in not working fully in Homekit Home.app

### ISSUE THREAD

**Issue by applemacgenius** [Brandawg93/homebridge-nest-cam#279]
**Before Submitting an Issue**

https://github.com/Brandawg93/homebridge-nest-cam/wiki/Troubleshooting

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest-cam`

Also include debug log output from startup through seeing the issue:
`homebridge -D`

**Describe the bug**
I had to configure it using the chrome trick by grabbing the token and the cookie.  So I see things in Home.app but when I click on the Nest widget it just spins and never fully shows the video live or Audio.  I'm not sure what to do.  I did have an error at 1 point "ENOTFOUND" but no clue why I got that. see below...it also seems to be slowing down my network.

[9/28/2020, 6:16:03 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:16:13 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:16:23 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:16:34 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:16:44 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:16:49 PM] [Nest-cam] Error checking alerts: ENOTFOUND
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:16:59 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:17:09 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:17:19 PM] [Nest-cam] Error checking alerts: ETIMEDOUT
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[9/28/2020, 6:19:31 PM] [Nest-cam] [NexusStreamer] Connected
[9/28/2020, 6:21:27 PM] [Nest-cam] [NexusStreamer] Connected
[9/28/2020, 6:21:37 PM] [Nest-cam] [NexusStreamer] Disconnected
**To Reproduce**

1. install the plugin
2. setup with token and cookie info (the other way did not work for me)
3. go to home.app
4. tape on the camera widget 
5. observe

**Expected behavior**
I except that when I click on the camera I see live video and audio 

Please answer these questions before submitting this issue:
```
On what OS are you running homebridge: 

homebridge-config-ui-x v4.27.2
Node.js Version | v12.18.4
Npm Version  v6.14.6

On what iOS version are you having issues: 
iOS 14.0
What camera types are having issues: NEST DropCam HD software version: 217-610040
Does this issue occur consistently or randomly: Always
If applicable, what was the last version that worked properly: none
```

**Comment by applemacgenius** [comment]
![Screenshot 2020-09-28 at 6 05 14 PM](https://user-images.githubusercontent.com/46770856/94503103-8d3c0d80-01ba-11eb-87d6-999b28098900.jpeg)

**Comment by Brandawg93** [comment]
I have added those error codes to the [Error Codes Wiki](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes). Essentially they mean that the device running homebridge is unable to connect to Nest, not because of Nest but because of the device itself. Usually, this occurs when someone is running Pihole or some other type of antivirus/spam tool.

**Comment by applemacgenius** [comment]
I have all Mac... no virus protection at all.. 


Jonathan Broskey
applemacgenius@icloud.com

**Comment by Brandawg93** [comment]
I'm not sure what other help I can provide from a plugin standpoint. Something internally is not allowing your homebridge service to connect to the Nest website. Not sure where you are located, but for me I'm in the US so the url homebridge is looking for is `https://nexusapi-us1.camera.home.nest.com`. Are you able to ping that from the homebridge device?

**Comment by applemacgenius** [comment]
% ping nexusapi-us1.camera.home.nest.com 
PING nexusapi-us1.camera.home.nest.com (130.211.9.222): 56 data bytes
64 bytes from 130.211.9.222: icmp_seq=0 ttl=116 time=13.812 ms
64 bytes from 130.211.9.222: icmp_seq=1 ttl=116 time=12.191 ms
64 bytes from 130.211.9.222: icmp_seq=2 ttl=116 time=22.086 ms
64 bytes from 130.211.9.222: icmp_seq=3 ttl=116 time=13.205 ms


Looks to work. hmmm

**Comment by applemacgenius** [comment]
I tried using the terminal script this time instead of manually scrubbing the chrome developer menu.. 

[9/29/2020, 3:09:29 PM] [Nest-cam] Access token acquisition via googleAuth failed (code ECONNREFUSED).
[9/29/2020, 3:09:29 PM] [Nest-cam] Retrying in 15 second(s).
[9/29/2020, 3:09:44 PM] [Nest-cam] Access token acquisition via googleAuth failed (code ECONNREFUSED).
[9/29/2020, 3:09:44 PM] [Nest-cam] Retrying in 15 second(s).

**Comment by Brandawg93** [comment]
ECONNREFUSED means that something on your local network refused the connection to Nest. Usually, it's the router's firewall.

**Comment by applemacgenius** [comment]
I edited my last comment.  I hit return too fast.

**Comment by applemacgenius** [comment]
[9/29/2020, 3:19:06 PM] [Nest-cam] [NexusStreamer] Connected
[9/29/2020, 3:19:06 PM] [Nest-cam] [NexusStreamer] Redirecting...
[9/29/2020, 3:19:06 PM] [Nest-cam] [NexusStreamer] Disconnected
[9/29/2020, 3:19:07 PM] [Nest-cam] [NexusStreamer] Connected
[9/29/2020, 3:19:36 PM] [Nest-cam] [NexusStreamer] Disconnected

seems ok, no error on the homebridge side... just the home.app opening up the widget

**Comment by Brandawg93** [comment]
The cameras could be cached in Homebridge. That's why you're still seeing them.

**Comment by Brandawg93** [comment]
I saw your edit. Try running homebridge in debug mode (homebridge -D) and see if anything stands out.

**Comment by applemacgenius** [comment]
[RPReplay_Final1601418255.mov.zip](https://github.com/Brandawg93/homebridge-nest-cam/files/5302142/RPReplay_Final1601418255.mov.zip)

**Comment by applemacgenius** [comment]
How would I do that if I am running the UI version?

**Comment by applemacgenius** [comment]
found it NVM

**Comment by applemacgenius** [comment]
[9/29/2020, 3:27:25 PM] [Nest-cam] Updating info for Dining Room Streaming
[9/29/2020, 3:27:25 PM] [Nest-cam] Checking for alerts on Dining Room
[9/29/2020, 3:27:25 PM] [Nest-cam] Updating info for Dining Room Audio
[9/29/2020, 3:27:26 PM] [Nest-cam] Stopped streaming session!
[9/29/2020, 3:27:32 PM] [Nest-cam] VIDEO command: ffmpeg -f,h264,-use_wallclock_as_timestamps,1,-r,30,-i,pipe:,-c:v,libx264,-preset,ultrafast,-tune,zerolatency,-pix_fmt,yuv420p,-payload_type,99,-ssrc,3511819,-f,rtp,-srtp_out_suite,AES_CM_128_HMAC_SHA1_80,-srtp_out_params,NoT/1xQVW9ztUgbcGtR0QuAnE4PCM41qFY7VVG8q,srtp://10.0.4.104:59900?rtcpport=59900&localrtcpport=51846&pkt_size=1378
[9/29/2020, 3:27:32 PM] [Nest-cam] AUDIO command: ffmpeg -c:a,libfdk_aac,-i,pipe:,-c:a,libfdk_aac,-profile:a,aac_eld,-ac,1,-ar,16k,-b:a,24k,-flags,+global_header,-payload_type,110,-ssrc,11783047,-f,rtp,-srtp_out_suite,AES_CM_128_HMAC_SHA1_80,-srtp_out_params,mZsrjdQk9CkiuifIKfPJdY5FlIUa6rCAfYjaWuVF,srtp://10.0.4.104:61514?rtcpport=61514&localrtcpport=51847&pkt_size=188
[9/29/2020, 3:27:32 PM] [Nest-cam] RETURN AUDIO command: ffmpeg -hide_banner,-protocol_whitelist,pipe,udp,rtp,file,crypto,-f,sdp,-c:a,libfdk_aac,-i,pipe:0,-map,0:0,-c:a,libspeex,-af,atempo=2.0,asetrate=16000/0.95,-frames_per_packet,2,-ac,1,-ar,16k,-f,data,pipe:1
[9/29/2020, 3:27:32 PM] [Nest-cam] waiting for socket to connect
[9/29/2020, 3:27:32 PM] [Nest-cam] Using HIGH quality stream.
[9/29/2020, 3:27:32 PM] [Nest-cam] waiting for socket to connect
[9/29/2020, 3:27:32 PM] [Nest-cam] VIDEO: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --enable-videotoolbox --pkgconfigdir=/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/lib/pkgconfig --prefix=/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace --pkg-config-flags=--static --extra-cflags=-I/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/include --extra-ldflags=-L/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[9/29/2020, 3:27:32 PM] [Nest-cam] AUDIO: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --enable-videotoolbox --pkgconfigdir=/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/lib/pkgconfig --prefix=/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace --pkg-config-flags=--static --extra-cflags=-I/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/include --extra-ldflags=-L/Users/runner/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] Connected
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] OK
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] Playback End
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] Redirect
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] Redirecting...
[9/29/2020, 3:27:33 PM] [Nest-cam] Using HIGH quality stream.
[9/29/2020, 3:27:33 PM] [Nest-cam] waiting for socket to connect
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] Disconnected
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] Connected
[9/29/2020, 3:27:33 PM] [Nest-cam] [NexusStreamer] OK
[9/29/2020, 3:27:34 PM] [Nest-cam] [NexusStreamer] Playback Begin
[9/29/2020, 3:27:35 PM] [Nest-cam] Checking for alerts on Dining Room
[9/29/2020, 3:27:36 PM] [Nest-cam] Setting Dining Room Sound Motion to false
[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: Input #0, h264, from 'pipe:':
  Duration: N/A, start: 1601418454.597032
[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: , bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 1200k tbn, 30 tbc

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: [swscaler @ 0x7fef98008000] deprecated pixel format used, make sure you did set range correctly

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: [libx264 @ 0x7fefd2809400] using SAR=1/1

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: [libx264 @ 0x7fefd2809400] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: [libx264 @ 0x7fefd2809400] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
Output #0, rtp, to 'srtp://10.0.4.104:59900?rtcpport=59900&localrtcpport=51846&pkt_size=1378':
  Metadata:
    encoder         : Lavf58.45.100

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO:     Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A

[9/29/2020, 3:27:36 PM] [Nest-cam] VIDEO: frame=   26 fps=0.0 q=17.0 size=     380kB time=00:00:00.83 bitrate=3740.4kbits/s dup=1 drop=0 speed=1.36x    
[9/29/2020, 3:27:37 PM] [Nest-cam] VIDEO: frame=   35 fps= 31 q=19.0 size=     466kB time=00:00:01.13 bitrate=3371.9kbits/s dup=1 drop=0 speed=1.01x    
[9/29/2020, 3:27:38 PM] [Nest-cam] VIDEO: frame=   44 fps= 25 q=19.0 size=     631kB time=00:00:01.43 bitrate=3603.9kbits/s dup=1 drop=0 speed=0.813x    
[9/29/2020, 3:27:38 PM] [Nest-cam] VIDEO: frame=   53 fps= 23 q=18.0 size=     754kB time=00:00:01.73 bitrate=3565.5kbits/s dup=1 drop=0 speed=0.749x    
[9/29/2020, 3:27:39 PM] [Nest-cam] VIDEO: frame=   62 fps= 21 q=18.0 size=     865kB time=00:00:02.03 bitrate=3483.7kbits/s dup=1 drop=0 speed=0.702x    
[9/29/2020, 3:27:39 PM] [Nest-cam] AUDIO: Input #0, aac, from 'pipe:':
  Duration: N/A, bitrate: 48 kb/s

[9/29/2020, 3:27:39 PM] [Nest-cam] AUDIO:     Stream #0:0: Audio: aac, 8000 Hz, mono, s16, 48 kb/s

[9/29/2020, 3:27:39 PM] [Nest-cam] VIDEO: frame=   71 fps= 20 q=17.0 size=     957kB time=00:00:02.33 bitrate=3360.2kbits/s dup=1 drop=0 speed=0.665x    
[9/29/2020, 3:27:39 PM] [Nest-cam] AUDIO: Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> aac (libfdk_aac))

[9/29/2020, 3:27:39 PM] [Nest-cam] AUDIO: Output #0, rtp, to 'srtp://10.0.4.104:61514?rtcpport=61514&localrtcpport=51847&pkt_size=188':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0
[9/29/2020, 3:27:39 PM] [Nest-cam] AUDIO: : Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libfdk_aac

[9/29/2020, 3:27:40 PM] [Nest-cam] VIDEO: frame=   80 fps= 19 q=17.0 size=    1048kB time=00:00:02.63 bitrate=3260.0kbits/s dup=1 drop=0 speed=0.641x    
[9/29/2020, 3:27:40 PM] [Nest-cam] AUDIO: size=      22kB time=00:00:06.22 bitrate=  28.3kbits/s speed=10.5x    
[9/29/2020, 3:27:41 PM] [Nest-cam] VIDEO: frame=   89 fps= 19 q=17.0 size=    1135kB time=00:00:02.93 bitrate=3168.4kbits/s dup=1 drop=0 speed=0.622x    
[9/29/2020, 3:27:41 PM] [Nest-cam] AUDIO: size=      24kB time=00:00:06.86 bitrate=  28.3kbits/s speed= 5.7x    
[9/29/2020, 3:27:41 PM] [Nest-cam] VIDEO: frame=   98 fps= 18 q=18.0 size=    1221kB time=00:00:03.23 bitrate=3093.9kbits/s dup=1 drop=0 speed=0.61x    
[9/29/2020, 3:27:41 PM] [Nest-cam] AUDIO: size=      26kB time=00:00:07.50 bitrate=  28.3kbits/s speed=4.18x    
[9/29/2020, 3:27:42 PM] [Nest-cam] VIDEO: frame=  107 fps= 18 q=18.0 size=    1395kB time=00:00:03.53 bitrate=3233.3kbits/s dup=1 drop=0 speed=0.597x    
[9/29/2020, 3:27:42 PM] [Nest-cam] AUDIO: size=      28kB time=00:00:08.01 bitrate=  28.3kbits/s speed=3.33x    
[9/29/2020, 3:27:42 PM] [Nest-cam] VIDEO: frame=  116 fps= 18 q=18.0 size=    1507kB time=00:00:03.83 bitrate=3220.6kbits/s dup=1 drop=0 speed=0.584x    
[9/29/2020, 3:27:43 PM] [Nest-cam] AUDIO: size=      30kB time=00:00:08.65 bitrate=  28.2kbits/s speed=2.89x    
[9/29/2020, 3:27:43 PM] [Nest-cam] VIDEO: frame=  125 fps= 17 q=18.0 size=    1597kB time=00:00:04.13 bitrate=3165.9kbits/s dup=1 drop=0 speed=0.578x    
[9/29/2020, 3:27:43 PM] [Nest-cam] AUDIO: size=      32kB time=00:00:09.29 bitrate=  28.2kbits/s speed=2.54x    
[9/29/2020, 3:27:44 PM] [Nest-cam] VIDEO: frame=  134 fps= 17 q=19.0 size=    1679kB time=00:00:04.43 bitrate=3103.1kbits/s dup=1 drop=0 speed=0.573x    
[9/29/2020, 3:27:44 PM] [Nest-cam] AUDIO: size=      34kB time=00:00:09.80 bitrate=  28.2kbits/s speed=2.35x    
[9/29/2020, 3:27:44 PM] [Nest-cam] VIDEO: frame=  143 fps= 17 q=18.0 size=    1783kB time=00:00:04.73 bitrate=3086.5kbits/s dup=1 drop=0 speed=0.568x    
[9/29/2020, 3:27:44 PM] [Nest-cam] AUDIO: size=      36kB time=00:00:10.44 bitrate=  28.2kbits/s speed=2.14x    
[9/29/2020, 3:27:45 PM] [Nest-cam] AUDIO: size=      37kB time=00:00:10.83 bitrate=  28.2kbits/s speed=2.01x    
[9/29/2020, 3:27:45 PM] [Nest-cam] VIDEO: frame=  150 fps= 17 q=17.0 size=    1845kB time=00:00:04.96 bitrate=3042.4kbits/s dup=1 drop=0 speed=0.56x    
[9/29/2020, 3:27:45 PM] [Nest-cam] Checking for alerts on Dining Room
[9/29/2020, 3:27:45 PM] [Nest-cam] VIDEO: frame=  155 fps= 16 q=17.0 size=    1893kB time=00:00:05.13 bitrate=3021.2kbits/s dup=1 drop=0 speed=0.544x    
[9/29/2020, 3:27:46 PM] [Nest-cam] AUDIO: size=      40kB time=00:00:11.59 bitrate=  28.2kbits/s speed=1.89x    
[9/29/2020, 3:27:46 PM] [Nest-cam] VIDEO: frame=  160 fps= 16 q=17.0 size=    1942kB time=00:00:05.30 bitrate=3002.0kbits/s dup=1 drop=0 speed=0.526x    
[9/29/2020, 3:27:46 PM] [Nest-cam] AUDIO: size=      42kB time=00:00:12.11 bitrate=  28.2kbits/s speed= 1.8x    
[9/29/2020, 3:27:47 PM] [Nest-cam] VIDEO: frame=  167 fps= 16 q=17.0 size=    2101kB time=00:00:05.53 bitrate=3111.2kbits/s dup=1 drop=0 speed=0.517x    
[9/29/2020, 3:27:47 PM] [Nest-cam] AUDIO: size=      45kB time=00:00:13.00 bitrate=  28.2kbits/s speed=1.77x    
[9/29/2020, 3:27:47 PM] [Nest-cam] VIDEO: frame=  176 fps= 16 q=15.0 size=    2171kB time=00:00:05.83 bitrate=3048.1kbits/s dup=1 drop=0 speed=0.52x    
[9/29/2020, 3:27:47 PM] [Nest-cam] AUDIO: size=      46kB time=00:00:13.51 bitrate=  28.2kbits/s speed=1.71x    
[9/29/2020, 3:27:48 PM] [Nest-cam] VIDEO: frame=  185 fps= 16 q=18.0 size=    2257kB time=00:00:06.13 bitrate=3014.2kbits/s dup=1 drop=0 speed=0.517x    
[9/29/2020, 3:27:48 PM] [Nest-cam] AUDIO: size=      49kB time=00:00:14.15 bitrate=  28.2kbits/s speed=1.66x    
[9/29/2020, 3:27:48 PM] [Nest-cam] VIDEO: frame=  194 fps= 16 q=18.0 size=    2349kB time=00:00:06.43 bitrate=2990.6kbits/s dup=1 drop=0 speed=0.516x    
[9/29/2020, 3:27:48 PM] [Nest-cam] RETURN AUDIO: Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:0':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A

[9/29/2020, 3:27:48 PM] [Nest-cam] RETURN AUDIO:     Stream #0:0: Audio: aac, 16000 Hz, mono, s16

[9/29/2020, 3:27:48 PM] [Nest-cam] RETURN AUDIO: Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> speex (libspeex))

[9/29/2020, 3:27:49 PM] [Nest-cam] AUDIO: size=      51kB time=00:00:14.79 bitrate=  28.2kbits/s speed=1.61x    
[9/29/2020, 3:27:49 PM] [Nest-cam] VIDEO: frame=  203 fps= 16 q=18.0 size=    2433kB time=00:00:06.73 bitrate=2960.5kbits/s dup=1 drop=0 speed=0.516x    
[9/29/2020, 3:27:49 PM] [Nest-cam] AUDIO: size=      53kB time=00:00:15.31 bitrate=  28.1kbits/s speed=1.57x    
[9/29/2020, 3:27:50 PM] [Nest-cam] VIDEO: frame=  212 fps= 15 q=17.0 size=    2530kB time=00:00:07.03 bitrate=2946.8kbits/s dup=1 drop=0 speed=0.513x    
[9/29/2020, 3:27:50 PM] [Nest-cam] AUDIO: size=      55kB time=00:00:15.95 bitrate=  28.2kbits/s speed=1.54x    
[9/29/2020, 3:27:50 PM] [Nest-cam] VIDEO: frame=  218 fps= 15 q=17.0 size=    2585kB time=00:00:07.23 bitrate=2927.7kbits/s dup=1 drop=0 speed=0.506x    
[9/29/2020, 3:27:51 PM] [Nest-cam] AUDIO: size=      57kB time=00:00:16.59 bitrate=  28.2kbits/s speed=1.52x    
[9/29/2020, 3:27:51 PM] [Nest-cam] VIDEO: frame=  230 fps= 15 q=18.0 size=    2802kB time=00:00:07.63 bitrate=3007.3kbits/s dup=1 drop=0 speed=0.514x    
[9/29/2020, 3:27:51 PM] [Nest-cam] AUDIO: size=      59kB time=00:00:17.10 bitrate=  28.1kbits/s speed=1.48x    
[9/29/2020, 3:27:51 PM] [Nest-cam] AUDIO: size=      60kB time=00:00:17.48 bitrate=  28.1kbits/s speed=1.45x    
[9/29/2020, 3:27:51 PM] [Nest-cam] VIDEO: frame=  239 fps= 15 q=18.0 size=    2899kB time=00:00:07.93 bitrate=2993.7kbits/s dup=1 drop=0 speed=0.508x    
[9/29/2020, 3:27:52 PM] [Nest-cam] VIDEO: frame=  251 fps= 15 q=14.0 size=    3181kB time=00:00:08.33 bitrate=3127.1kbits/s dup=1 drop=0 speed=0.513x    
[9/29/2020, 3:27:52 PM] [Nest-cam] AUDIO: size=      63kB time=00:00:18.38 bitrate=  28.1kbits/s speed=1.44x    
[9/29/2020, 3:27:53 PM] [Nest-cam] VIDEO: frame=  259 fps= 15 q=18.0 size=    3234kB time=00:00:08.60 bitrate=3080.5kbits/s dup=1 drop=0 speed=0.513x    
[9/29/2020, 3:27:53 PM] [Nest-cam] AUDIO: size=      65kB time=00:00:18.89 bitrate=  28.1kbits/s speed=1.42x    
[9/29/2020, 3:27:53 PM] [Nest-cam] VIDEO: frame=  266 fps= 15 q=17.0 size=    3297kB time=00:00:08.83 bitrate=3057.7kbits/s dup=1 drop=0 speed=0.509x    
[9/29/2020, 3:27:53 PM] [Nest-cam] AUDIO: size=      67kB time=00:00:19.53 bitrate=  28.1kbits/s speed= 1.4x    
[9/29/2020, 3:27:54 PM] [Nest-cam] VIDEO: frame=  276 fps= 15 q=16.0 size=    3388kB time=00:00:09.16 bitrate=3027.7kbits/s dup=1 drop=0 speed=0.512x    
[9/29/2020, 3:27:54 PM] [Nest-cam] AUDIO: size=      69kB time=00:00:20.17 bitrate=  28.1kbits/s speed=1.39x    
[9/29/2020, 3:27:54 PM] [Nest-cam] VIDEO: frame=  284 fps= 15 q=19.0 size=    3534kB time=00:00:09.43 bitrate=3069.1kbits/s dup=1 drop=0 speed=0.512x    
[9/29/2020, 3:27:55 PM] [Nest-cam] AUDIO: size=      71kB time=00:00:20.68 bitrate=  28.1kbits/s speed=1.37x    
[9/29/2020, 3:27:55 PM] [Nest-cam] VIDEO: frame=  293 fps= 15 q=18.0 size=    3656kB time=00:00:09.73 bitrate=3077.2kbits/s dup=1 drop=0 speed=0.511x    
[9/29/2020, 3:27:55 PM] [Nest-cam] AUDIO: size=      73kB time=00:00:21.32 bitrate=  28.1kbits/s speed=1.36x    
[9/29/2020, 3:27:55 PM] [Nest-cam] Checking for alerts on Dining Room
[9/29/2020, 3:27:56 PM] [Nest-cam] VIDEO: frame=  302 fps= 15 q=18.0 size=    3755kB time=00:00:10.03 bitrate=3066.0kbits/s dup=1 drop=0 speed=0.511x    
[9/29/2020, 3:27:56 PM] [Nest-cam] AUDIO: size=      75kB time=00:00:21.96 bitrate=  28.1kbits/s speed=1.35x    
[9/29/2020, 3:27:56 PM] [Nest-cam] VIDEO: frame=  311 fps= 15 q=17.0 size=    3861kB time=00:00:10.33 bitrate=3060.7kbits/s dup=1 drop=0 speed=0.511x    
[9/29/2020, 3:27:57 PM] [Nest-cam] AUDIO: size=      78kB time=00:00:22.60 bitrate=  28.1kbits/s speed=1.33x    
[9/29/2020, 3:27:57 PM] [Nest-cam] VIDEO: frame=  319 fps= 15 q=20.0 size=    3941kB time=00:00:10.60 bitrate=3046.1kbits/s dup=1 drop=0 speed=0.511x    
[9/29/2020, 3:27:57 PM] [Nest-cam] AUDIO: size=      79kB time=00:00:23.11 bitrate=  28.1kbits/s speed=1.31x    
[9/29/2020, 3:27:57 PM] [Nest-cam] VIDEO: frame=  326 fps= 15 q=18.0 size=    4009kB time=00:00:10.83 bitrate=3031.4kbits/s dup=1 drop=0 speed=0.507x    
[9/29/2020, 3:27:58 PM] [Nest-cam] AUDIO: size=      82kB time=00:00:23.88 bitrate=  28.1kbits/s speed= 1.3x    
[9/29/2020, 3:27:58 PM] [Nest-cam] VIDEO: frame=  336 fps= 15 q=16.0 size=    4109kB time=00:00:11.16 bitrate=3014.0kbits/s dup=1 drop=0 speed=0.51x    
[9/29/2020, 3:27:58 PM] [Nest-cam] VIDEO: frame=  344 fps= 15 q=19.0 size=    4261kB time=00:00:11.43 bitrate=3052.9kbits/s dup=1 drop=0 speed=0.509x    
[9/29/2020, 3:27:58 PM] [Nest-cam] AUDIO: size=      84kB time=00:00:24.52 bitrate=  28.1kbits/s speed= 1.3x    
[9/29/2020, 3:27:59 PM] [Nest-cam] VIDEO: frame=  352 fps= 15 q=17.0 size=    4376kB time=00:00:11.70 bitrate=3063.8kbits/s dup=1 drop=0 speed=0.51x    
[9/29/2020, 3:27:59 PM] [Nest-cam] AUDIO: size=      86kB time=00:00:25.16 bitrate=  28.1kbits/s speed=1.29x    
[9/29/2020, 3:27:59 PM] [Nest-cam] VIDEO: frame=  360 fps= 15 q=16.0 size=    4477kB time=00:00:11.96 bitrate=3064.7kbits/s dup=1 drop=0 speed=0.509x    
[9/29/2020, 3:28:00 PM] [Nest-cam] AUDIO: size=      89kB time=00:00:25.80 bitrate=  28.1kbits/s speed=1.28x    
[9/29/2020, 3:28:00 PM] [Nest-cam] VIDEO: frame=  368 fps= 15 q=18.0 size=    4558kB time=00:00:12.23 bitrate=3052.0kbits/s dup=1 drop=0 speed=0.506x    
[9/29/2020, 3:28:00 PM] [Nest-cam] AUDIO: size=      90kB time=00:00:26.31 bitrate=  28.1kbits/s speed=1.27x    
[9/29/2020, 3:28:01 PM] [Nest-cam] VIDEO: frame=  378 fps= 15 q=17.0 size=    4653kB time=00:00:12.56 bitrate=3032.9kbits/s dup=1 drop=0 speed=0.509x    
[9/29/2020, 3:28:01 PM] [Nest-cam] AUDIO: size=      93kB time=00:00:26.95 bitrate=  28.1kbits/s speed=1.26x    
[9/29/2020, 3:28:01 PM] [Nest-cam] VIDEO: frame=  384 fps= 15 q=16.0 size=    4725kB time=00:00:12.76 bitrate=3032.0kbits/s dup=1 drop=0 speed=0.506x    
[9/29/2020, 3:28:02 PM] [Nest-cam] AUDIO: size=      95kB time=00:00:27.59 bitrate=  28.1kbits/s speed=1.26x    
[9/29/2020, 3:28:02 PM] [Nest-cam] VIDEO: frame=  394 fps= 15 q=17.0 size=    4821kB time=00:00:13.10 bitrate=3014.7kbits/s dup=1 drop=0 speed=0.509x    
[9/29/2020, 3:28:02 PM] [Nest-cam] AUDIO: size=      96kB time=00:00:28.11 bitrate=  28.1kbits/s speed=1.25x    
[9/29/2020, 3:28:02 PM] [Nest-cam] Stopped streaming session!
[9/29/2020, 3:28:02 PM] [Nest-cam] VIDEO: frame=  401 fps= 15 q=23.0 size=    4931kB time=00:00:13.33 bitrate=3029.5kbits/s dup=1 drop=0 speed=0.507x    
[9/29/2020, 3:28:02 PM] [Nest-cam] VIDEO: frame=  401 fps= 15 q=23.0 Lsize=    4931kB time=00:00:13.33 bitrate=3029.5kbits/s dup=1 drop=0 speed=0.507x    
video:4878kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.092547%

[9/29/2020, 3:28:02 PM] [Nest-cam] VIDEO: [libx264 @ 0x7fefd2809400] frame I:2     Avg QP:17.00  size:141316
[libx264 @ 0x7fefd2809400] frame P:399   Avg QP:17.51  size: 11810
[libx264 @ 0x7fefd2809400] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x7fefd2809400] 
[9/29/2020, 3:28:02 PM] [Nest-cam] VIDEO: mb P  I16..4:  1.0%  0.0%  0.0%  P16..4: 36.3%  0.0%  0.0%  0.0%  0.0%    skip:62.7%
[libx264 @ 0x7fefd2809400] coded y,uvDC,uvAC intra: 83.7% 72.8% 19.6% inter: 13.2% 13.9% 0.9%
[libx264 @ 0x7fefd2809400] i16 v,h,dc,p: 13% 18% 53% 16%
[libx264 @ 0x7fefd2809400] i8c dc,h,v,p: 54% 20% 18%  8%
[libx264 @ 0x7fefd2809400] kb/s:2989.32

[9/29/2020, 3:28:02 PM] [Nest-cam] VIDEO: Exiting normally, received signal 15.

[9/29/2020, 3:28:02 PM] [Nest-cam] Stopped streaming session!
[9/29/2020, 3:28:02 PM] [Nest-cam] [NexusStreamer] Disconnected
[9/29/2020, 3:28:06 PM] [Nest-cam] Checking for alerts on Dining Room

**Comment by applemacgenius** [comment]
could it be the "ffmpeg" ?

**Comment by Brandawg93** [comment]
I wouldn't think so. That debug output looks good to me. Seems like the ENOTFOUND and ETIMEOUT errors are gone. Just no streaming?

**Comment by applemacgenius** [comment]
correct no stream :-(

**Comment by Brandawg93** [comment]
What version of homebridge are you using? I've heard that the latest version (v1.2.3) has some issues with streaming and that reverting to v1.1.6 fixes them.

**Comment by applemacgenius** [comment]
Node.js version - v14.12.0
Npm Version - v6.14.8
Homebridge-config-ui-x - v4.27.2

Version 1.2.3

**Comment by Brandawg93** [comment]
The homebridge team has reverted the latest version of homebridge from 1.2.3 back to 1.1.6. Reverting should fix this issue until the homebridge team releases an official fix.

**Comment by applemacgenius** [comment]
I reverted to 1.1.6 and it did not solve the issue.


 
Jonathan Broskey
applemacgenius@icloud.com

**Comment by mzaur** [comment]
I have the same issue. THe strange thing is that if I open the Home app and just leave it open with 'Favorite cameras' view, the thumbnails do update every 10-11 seconds. But if I tap to stream, there's the loading circle and then it times out with camera not responding. I tried reverting to 1.1.6 and also the latest beta 1.3.0 beta 14 - none of these fixed this. I checked debug log and there's no errors. 

Is this definitely a homebridge issue and not with the plugin? I checked their git and don't see any relevant issues, unless I'm missing it ?

**Comment by Brandawg93** [comment]
I'm fairly certain it's a homebridge issue as most all the other camera plugins have the same issue. It doesn't affect everyone, just a small subset of users. The homebridge team is aware of the issue, though.

**Comment by jamesngob** [comment]
Hello Brandawg93,

I just want to add this error into here as well. And the only way to fix this is to reboot the Homebridge server. I am running the Homebridge server as docker on Qnap NAS though, Homebridge version v1.2.3; FFmpeg version v4.3.1 built-in (I did not install any other FFmpeg so it should be built-in with Homebridge-Nest plugin).
And when this error show up, the Nest Camera will not responding, just as the same problem as above

[Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2189:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at Http2Stream.onStreamClose (internal/http2/core.js:510:12) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}

**Comment by bkowalk** [comment]
Just wanted to add that I’m seeing the same issue. Only on one out of 7 cams, though! Super strange. I’ll keep an eye on the thread and the homebridge issue. Thanks for the awesome plugin! I use this many times a day to get a PIP of my toddler’s room. Super nice.

**Comment by bkowalk** [comment]
Wanted to add an update - I was having the same issue, but finally saw things fixed this last time I ran Homebridge when I allowed ffmpeg through the windows firewall. I'm unsure what made that prompt finally pop up this time, but the request showed up to check if ffmpeg should be able to communicate on private networks. Clicking "allow" has finally started letting streams through.

Things I was doing, in case this helps anyone:
- running powershell in admin mode
- had hb-service stopped, ran an upgrade to homebridge-config-ui-x
- ran `homebridge -D`, started a camera stream.

Hopefully someone's having the same issue and tweaking firewall settings helps solve things as it did for me!

**Comment by Brandawg93** [comment]
Homebridge v1.2.4 was just released. If the release fixes this issue, please let me know here.

**Comment by hugocarmona7** [comment]
I just update to v1.2.4 and still having the same issue.

**Comment by Brandawg93** [comment]
Anyone know if this is fixed in v1.1.7?

**Comment by bobster16** [comment]
Mine started having this same NexusStreamer issue 5 days ago. Reset the Nest token and cookie, and updated homebridge to 1.2.5, downgraded to 1.1.6, but still nothing fixed it.

**Comment by Brandawg93** [comment]
@bobster16, there may be a potential fix by @supereg implemented into the latest beta of Homebridge ([v1.3.0](https://www.npmjs.com/package/homebridge/v/1.3.0-beta.41)) could you try that and let me know if it fixes your issue?

**Comment by bobster16** [comment]
@Brandawg93 Updated to 1.3.0-beta.41. Got the same issues but had a little more info. Pasting the log below. I will gladly switch to debug mode and send that novel over if it will help. 

04/01/2021, 15:47:16] [Nest-cam] [NexusStreamer] Connected
[04/01/2021, 15:47:16] [Nest-cam] [NexusStreamer] Redirecting...
[04/01/2021, 15:47:16] [Nest-cam] [NexusStreamer] Disconnected
[04/01/2021, 15:47:16] [Nest-cam] [NexusStreamer] Connected
[Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Big Brother 👀' was slow to respond!
[04/01/2021, 15:47:45] [Nest-cam] [NexusStreamer] Disconnected
(node:2447) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
(node:2447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bobster16** [comment]
...and now it's working this morning. The logs say it is still slow to respond, but I'm getting a live feed.  “¯\_(ツ)_/¯“

**Comment by Brandawg93** [comment]
@bobster16 Thanks for the heads up. My guess is that you unintentionally downloaded beta 40. NPM likes to cache releases so if you do something like `npm install homebridge@beta` (which is what the UI is doing for you) directly after it was updated, you may still get an older beta.

**Comment by bobster16** [comment]
@Brandawg93 I had selected .41 in the UI and the log shows my call for .41 instead of just calling the latest generic beta. 

I reviewed the logs from overnight and it looks like a few ETIMEDOUTs from the Nest-Cam plugin. Not sure if a reconnect made it happy again.

There were also a few ECONNRESETs from the Nest plugin. Slightly unrelated, but happened around some of the timeouts.

**Comment by Brandawg93** [comment]
Ok. Those are usually due to rate limiting on Nest's side. Glad to hear it's working for you! If anything changes, just let me know, and I'll take a look

**Comment by onixx** [comment]
Same issue here. However installing .42 did not resolve it.

I did some debugging to try to discover what is happening. Hopefully it can help resolve the problem.

1. Steam is starting on homebridge when clicking the camera. I see it in the debug log. There is nothing apparent in debug that there is an issue going on. However iphone receives nothing and eventually times out.

2. tcpdump shows the traffic flowing from homebridge to iphone or home hub  to iphone if not on local network (depending where the user requesting the stream is). Interesting there however there are ICMP unreacheable messages flowing. a lot of them. it appear to me that this is where there's an issue with the steam and destination ports

see tcpdump when requesting stream while not on local network
192.168.10.223 is homepod
192.168.10.1 is router
67.69.76.91 is current public address of iphone

root@jetstream:~# tcpdump -i eth0 -n | grep unrea
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
08:30:56.577959 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:30:57.100757 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:30:58.125297 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:30:59.078662 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:31:00.127257 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:31:01.196895 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:31:02.118543 IP 192.168.10.1 > 192.168.10.223: ICMP 192.168.10.1 udp port 38593 unreachable, length 114
08:31:02.826661 IP 192.168.10.223 > 67.69.76.91: ICMP 192.168.10.223 udp port 16405 unreachable, length 36
08:31:03.141971 IP 192.168.10.223 > 67.69.76.91: ICMP 192.168.10.223 udp port 16405 unreachable, length 36

**Comment by geoffreyspencer** [comment]
Has this been resolved yet? How do I turn on more comprehensive debugging for the Nest Cams plugin? I see no errors in the regular logs but no cameras are being listed at all in the Home Bridge logs. I see the cams listed in the Accessories list but nothing is appearing in HomeKit. The Settings is correct because it listed my username correctly.

**Comment by Brandawg93** [comment]
This has not been resolved because it is not a plugin issue. It sounds like you may need to delete your accessory cache. If that doesn't work, I'd recommend redoing your homebridge setup.

**Comment by pjbarnett** [comment]
Just wondered if this is similar in any way. However my cameras do work but not all the time. Sometimes they connect and work other times I get a no responding error.
I'm on 1.1.7. I attempted to try 1.3.0 to see if it resolved it however I have another plug-in that then ignores a 60s poll and does it every 5s so had to revert for now!

**Comment by judas2720** [comment]
Clearing accessory cache for the camera only seemed to resolve my issue. Was getting the conversion error in logs and not responding in home app. Using HB UI 4.37.0 and nest-cam 7.1.0, nest hello.

**Comment by Brandawg93** [comment]
For anyone still having issues with this, I was able to fix my setup by going to `Homebridge Settings` in the UI and selecting the correct interface in `Network Interfaces` (`eth0` for me).

**Comment by cscott365** [comment]
Even after selecting the correct network interface, I am still seeing SRTP output to an address that is NOT part of my network. It is not getting the correct interface for the stream so that I can access it.

**Comment by Brandawg93** [comment]
Ok. The plugin uses the IP address supplied by Homebridge/HomeKit. If everything is up-to-date, then there is nothing I can do from a plugin standpoint to force it to stream to the correct up address.

**Comment by cscott365** [comment]
Absolutely get that. Do you know the area of the Homebridge that is determining the IP? Would love to track that down and for now hardcode it and provide feedback to that team. As always, your support is fabulous, even when it is not the fault of your plugin.

**Comment by Brandawg93** [comment]
To offer a little more clarity, the original issue for this thread was due to the new Ciao library (introduced in homebridge v1.3.0) not broadcasting mDNS properly. Forcing it in the settings allows the user to control the IP address broadcasted by mDNS. 

Your situation is a little different. When you attempt to stream from a device, that device sends its IP address via HomeKit to Homebridge where I pick it up and tell the plugin to stream to it. That IP address will change each time you use a different device to stream and is supplied by HomeKit. I don't think there is much the Homebridge team will be able to do to help, but maybe they could offer a little more insight.

**Comment by cscott365** [comment]
The clarity helped. It appears that my issue is that Homekit is picking up the IP address of my IOS VPN and not the internal IP for the WiFi and sending that to Homebridge for RTP. If I disconnect from the VPN it works. Even though all other local connections work just fine, this specific video stream seems to now work. Thanks for the clarity!! I can stop pulling out what hair I had left.

**Comment by Brandawg93** [comment]
If anyone still has this issue after updating Homebridge to v1.3.1 and forcing the correct IP in settings, feel free to submit a new issue.
